dist: bionic

services:
  - docker

stages:
  - test
  - name: dockerize
    if: branch = master AND type = push

jobs:
  include:
    - stage: test

      script:
        - python -c "import pspipe"

    - stage: dockerize

      script:
        - echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USER}" --password-stdin;
        #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t cmb/pspipe .
        - docker images

      after_success:
        - docker tag cmb/pspipe:latest ${DOCKERHUB_ORG}/pspipe:latest
        - docker push ${DOCKERHUB_ORG}/pspipe:latest
