dist: bionic

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - docker

stages:
  - test
  - name: dockerize
    if: branch = master AND type = push

jobs:
  include:
    - stage: test

      before_install:
        - sudo apt-get update
        - sudo apt-get -y install automake build_essential gfortran libcfitsio-dev libfftw3-dev libgsl-dev libchealpix-dev
        - gfortran --version
        - python3 --version
        - python3 -m pip install --upgrade pip numpy cython

      install:
        - python3 -m pip install .

      script:
        - python -c "import pspipe"

    - stage: dockerize

      script:
        - echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USER}" --password-stdin;
        #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t cmb/pspipe .
        - docker images

      after_success:
        - docker tag cmb/pspipe:latest ${DOCKERHUB_ORG}/pspipe:latest
        - docker push ${DOCKERHUB_ORG}/pspipe:latest
