all: 
	make -C  wigner3j
	make -C  mcm_fortran
	make -C  cov_fortran

clean: wigner3j_clean mcm_fortran_clean mcm_fortran_clean

wigner3j_clean: 
	make -C wigner3j clean

mcm_fortran_clean:
	make -C mcm_fortran clean

mcm_fortran_clean:
	make -C mcm_fortran clean