# Set directory where all pipeline products will be stored
product_dir: products/mnms

# Set path to the dict file: __pspipe_root__ is a placeholder that is going to be replaced when
# parsing the yaml file by the location to the pspipe installation
config_file: __pspipe_root__/project/data_analysis/paramfiles/global_dr6_v4.dict

slurm:
  precmd: |
    source __base_dir__/setup.sh
  qos: regular
  account: mp107b
  constraint: cpu
  array: 0-1
  nodes: 4
  time: 04:00:00
  output: logs/pipeline_mnms_%A_%a.log
  job_name: mnms

pipeline:
  # Monte Carlo correction to the covariance matrix
  montecarlo/mc_mnms_get_nlms:
    slurm:
      ntasks: 8
      cpus_per_task: 128
    kwargs: &kwargs --bunch $SLURM_ARRAY_TASK_ID --nbunch 50
  montecarlo/mc_mnms_get_spectra_from_nlms:
    slurm:
      ntasks: 16
      cpus_per_task: 64
    kwargs: *kwargs
