# Set directory where all pipeline products will be stored
product_dir: products/dr6

# Set path to the dict file: __pspipe_root__ is a placeholder that is going to be replaced when
# parsing the yaml file by the location to the pspipe installation
config_file: !concat [__pspipe_root__, project/ACT_DR6/paramfiles/global_dr6v4_bin50.dict]

# Set location of scripts: default to pspipe_root/project/ACT_DR6/python
script_base_dir: null


pipeline:
  get_mcm_and_bbl:
    slurm:
      ntasks: 5
      cpus_per_task: 48
  get_alms:
    slurm:
      ntasks: 5
      cpus_per_task: 48
  get_spectra_from_alms:
    slurm:
      ntasks: 5
      cpus_per_task: 48
  get_best_fit_mflike: null
  get_noise_model: null
  get_sq_windows_alms:
    slurm:
      ntasks: 7
      cpus_per_task: 36
  get_covariance_blocks:
    slurm:
      nodes: 4
      ntasks: 16
      cpus_per_task: 64
    minimal_needed_time: 02:00:00
  get_beam_covariance:
    slurm:
      ntasks: 20
      cpus_per_task: 12
  get_xarrays_covmat: null

  # Leakage correction/covariance
  leakage/get_leakage_corrected_spectra_per_split:
    slurm:
      ntasks: 20
      cpus_per_task: 12
  leakage/get_leakage_sim:
    slurm:
      ntasks: 20
      cpus_per_task: 12
  leakage/get_leakage_covariance: null

  # Monte Carlo correction to the covariance matrix
  montecarlo/mc_analysis: null
  montecarlo/mc_cov_analysis: null
  montecarlo/mc_plot_spectra: null
  montecarlo/mc_cov_analysis_for_gp: null
  montecarlo/get_mc_corrected_xarrays_covmat_gp: null
  montecarlo/mc_apply_syst_model : 
    slurm:
      ntasks: 20
      cpus_per_task: 12
  montecarlo/mc_get_combined_syst_spectra:
      slurm:
        ntasks: 20
        cpus_per_task: 12

  montecarlo/mc_analyze_combined_syst_spectra: null

  # Aberration correction
  aberration/get_aberration_corrected_spectra: null

  # Radio and tSZ trispectrum
  non_gaussian_fg/get_connected_trispectrum_radio: null
  non_gaussian_fg/get_connected_trispectrum_tSZ: null
  non_gaussian_fg/get_connected_trispectrum_CIB: null

  # Non gaussian lensing terms (need prerun of CLASS)
  lensing/lensing_combine_cov_mat: null

  # Array null test
  null_tests/compute_null_tests: null

  # Combine cov mat and write data in a SACC file
  get_combined_cov_mats: null
  port2sacc: null
