# This configuration file shows how to build a yaml file to submit MCMC jobs in batch mode.

# Set directory where all pipeline products will be stored
product_dir: products/mcmc

# No config file is required for this special run
config_file: false

slurm:
  precmd: |
    source $BASE_DIR/setup.sh
  qos: regular
  account: mp107b
  constraint: cpu
  nodes: 1
  time: 0-48:00:00
  output: logs/pipeline_mcmc.log
  job_name: mcmc

# Monte Carlo markov chain
pipeline:
  # Install likelihoods and Boltzmann solver
  mcmc/cobaya_install:
    cmd: cobaya-install --just-data
    kwargs: &kwargs -p packages __pspipe_root__/project/ACT_DR6/yaml/DR6base.yml

  # This step will be done automatically when ACT DR6 data file will be released and installed via
  # the previous command
  mcmc/install_sacc_file:
    cmd: |
      cp /global/cfs/cdirs/act/data/tlouis/dr6v4/final_products/dr6_main/sacc/dr6_data_sacc_oct22.fits packages/data/ACTDR6MFLike/v0.1/.

  mcmc/cobaya_run:
    cmd: cobaya-run --resume
    slurm:
      ntasks: 4
    kwargs: *kwargs
