# Set directory where all pipeline products will be stored
product_dir: products/dr6xlegacy

# Set path to the dict file: __pspipe_root__ is a placeholder that is going to be replaced when
# parsing the yaml file by the location to the pspipe installation
config_file: !concat [__pspipe_root__, project/ACT_DR6/paramfiles/global_dr6v4xlegacy.dict]

variables:
  maps_Planck_f100:
    - planck_projected/HFI_SkyMap_2048_R3.01_halfmission-1_f100_map_srcfree.fits
    - planck_projected/HFI_SkyMap_2048_R3.01_halfmission-2_f100_map_srcfree.fits
  maps_Planck_f143:
    - planck_projected/HFI_SkyMap_2048_R3.01_halfmission-1_f143_map_srcfree.fits
    - planck_projected/HFI_SkyMap_2048_R3.01_halfmission-2_f143_map_srcfree.fits
  maps_Planck_f217:
    - planck_projected/HFI_SkyMap_2048_R3.01_halfmission-1_f217_map_srcfree.fits
    - planck_projected/HFI_SkyMap_2048_R3.01_halfmission-2_f217_map_srcfree.fits
  beam_T_Planck_f100 : beams/legacy/bl_T_legacy_100hm1x100hm2.dat
  beam_T_Planck_f143 : beams/legacy/bl_T_legacy_143hm1x143hm2.dat 
  beam_T_Planck_f217 : beams/legacy/bl_T_legacy_217hm1x217hm2.dat
  beam_pol_Planck_f100 : beams/legacy/bl_pol_legacy_100hm1x100hm2.dat
  beam_pol_Planck_f143 : beams/legacy/bl_pol_legacy_143hm1x143hm2.dat
  beam_pol_Planck_f217 : beams/legacy/bl_pol_legacy_217hm1x217hm2.dat


pipeline:
  # Planck maps pre-processing

  planck/project_planck_maps:
    slurm:
      ntasks: 8
      cpus_per_task: 32
      
  planck/extract_planck_beam: null
  planck/reformat_source_catalog: null
  planck/source_legacy_subtraction:
    script_file: planck/run_legacy_src_subtraction.sh
    # Mandatory here since the script already use `srun` commands
    slurm: false
  planck/check_src_subtraction:
    slurm:
      ntasks: 16

  # ACT/Planck cross correlation
  get_mcm_and_bbl:
    slurm:
      ntasks: 12
      cpus_per_task: 20
  get_alms:
    slurm:
      ntasks: 8
      cpus_per_task: 32
  get_spectra_from_alms:
    slurm:
      ntasks: 8
      cpus_per_task: 32
  get_best_fit_mflike: null
  get_noise_model: null
  get_sq_windows_alms:
    slurm:
      ntasks: 7
      cpus_per_task: 36
  get_covariance_blocks:
    slurm:
      nodes: 2
      ntasks: 8
      cpus_per_task: 64
    minimal_needed_time: 02:00:00

  # Leakage correction/covariance
  leakage/get_leakage_corrected_spectra_per_split:
    slurm:
      ntasks: 20
      cpus_per_task: 12
  leakage/get_leakage_sim:
    slurm:
      ntasks: 20
      cpus_per_task: 12
  leakage/get_leakage_covariance: null

  planck/get_corrected_planck_spectra: null
  # Calibration and polarisation efficiency
  calibration/get_calibs: null
  calibration/get_polar_eff_LCDM: null

  montecarlo/mc_analysis: null
  montecarlo/mc_cov_analysis: null
#  montecarlo/mc_plot_spectra: null
#  montecarlo/mc_plot_covariances: null

  # Computation of the Transfer Function
  mm_transfer_function/compute_tf: null
  mm_transfer_function/plot_all_tf:
    force: true

  

