# Set directory where all pipeline products will be stored
product_dir: products/dust

# Set path to the dict file: __pspipe_root__ is a placeholder that is going to be replaced when
# parsing the yaml file by the location to the pspipe installation
config_file: !concat [__pspipe_root__, project/data_analysis/paramfiles/global_dust.dict]

pipeline:
  get_mcm_and_bbl:
    slurm:
      ntasks: 3
      cpus_per_task: 64
  get_alms:
    slurm:
      ntasks: 2
      cpus_per_task: 128
  get_spectra_from_alms:
    slurm:
      ntasks: 3
      cpus_per_task: 64
  get_best_fit_mflike: null
  get_noise_model: null
  get_sq_windows_alms:
    slurm:
      ntasks: 3
      cpus_per_task: 64
  get_covariance_blocks:
    slurm:
      ntasks: 6
      cpus_per_task: 42
  fit_dust_amplitude.{mode}:
    script_file: dust/fit_dust_amplitude
    matrix:
      mode:
        - TT
        - TE
        - EE
        - BB
        - TB
    kwargs: --mode "{mode}"
