# This configuration file shows how to build a yaml file to submit MCMC jobs in batch mode.

# Use the same directory as DR6 pipeline to get the sacc file produced by the pipeline. MCMC
# products will be stored within product_dir/mcmc directory
product_dir: products/dr6

# No config file is required for this special run
config_file: false

slurm:
  precmd: |
    source $BASE_DIR/setup.sh
  qos: regular
  account: mp107b
  constraint: cpu
  nodes: 1
  time: 0-48:00:00
  output: logs/pipeline_mcmc.log
  job_name: mcmc

# Monte Carlo markov chain
pipeline:
  # Script to prepare cobaya run with reference to sacc file produced by DR6 pipeline. The script
  # also installs other likelihood data via cobaya-install program (only data and no code since it
  # will overload our camb+cosmorec installation)
  mcmc/prepare_mcmc: null

  # Test if everything looks ok
  mcmc/cobaya_test:
    cmd: cobaya-run --test
    kwargs: &kwargs mcmc/DR6base.yaml

  # Run cobaya sampler (force: true means the program can be rerun from the last sampled point)
  mcmc/cobaya_run:
    cmd: cobaya-run --resume
    force: true
    slurm:
      ntasks: 4
    kwargs: *kwargs

  mcmc/plot_mcmc:
    force: true
    kwargs: --getdist-yaml __pspipe_root__/project/ACT_DR6/python/mcmc/getdist.yml
