# Set directory where all pipeline products will be stored
product_dir: products/dr6xlegacy

# Set path to the dict file: __pspipe_root__ is a placeholder that is going to be replaced when
# parsing the yaml file by the location to the pspipe installation
config_file: !concat [__pspipe_root__, project/data_analysis/paramfiles/global_dr6v4xlegacy.dict]


pipeline:
  # Planck maps pre-processing
  planck/project_planck_maps:
    slurm:
      ntasks: 8
      cpus_per_task: 32
  planck/extract_planck_beam: null
  planck/reformat_source_catalog: null
  planck/source_legacy_subtraction:
    script_file: planck/run_legacy_src_subtraction.sh
    # Mandatory here since the script already use `srun` commands
    slurm: false
  planck/check_src_subtraction:
    slurm:
      ntasks: 16

  # ACT/Planck cross correlation
  get_window_dr6:
    slurm:
      ntasks: 5
      cpus_per_task: 48
  get_mcm_and_bbl:
    slurm:
      ntasks: 12
      cpus_per_task: 20
  get_alms:
    slurm:
      ntasks: 8
      cpus_per_task: 32
  get_spectra_from_alms:
    slurm:
      ntasks: 8
      cpus_per_task: 32
  get_best_fit_mflike: null
  get_noise_model: null
  get_sq_windows_alms:
    slurm:
      ntasks: 7
      cpus_per_task: 36
  get_covariance_blocks:
    slurm:
      nodes: 2
      ntasks: 8
      cpus_per_task: 64
    minimal_needed_time: 02:00:00

  # Leakage correction/covariance
  leakage/get_leakage_corrected_spectra_per_split:
    slurm:
      ntasks: 20
      cpus_per_task: 12
  leakage/get_leakage_sim:
    slurm:
      ntasks: 20
      cpus_per_task: 12
  leakage/get_leakage_covariance: null

  # End-to-end sim correction
  planck/get_planck_spectra_correction_from_nlms:
    slurm:
      nodes: 4
      ntasks: 32
      cpus_per_task: 32
    minimal_needed_time: 03:00:00
  montecarlo/mc_analysis: null
  planck/get_corrected_planck_spectra: null

  # Calibration and polarisation efficiency
  calibration/get_calibs: null
  calibration/get_polar_eff_LCDM: null

  # Simulations
  montecarlo/mc_mnms_get_nlms:
    slurm:
      nodes: 2
      ntasks: 4
      cpus_per_task: 128
    minimal_needed_time: 03:30:00
  planck/get_planck_sim_nlms:
    slurm:
      ntasks: 64
      cpus_per_task: 4
  montecarlo/mc_mnms_get_spectra_from_nlms:
    slurm:
      nodes: 4
      ntasks: 16
      cpus_per_task: 64

  montecarlo/mc_analysis: null
  montecarlo/mc_cov_analysis: null
  montecarlo/mc_plot_spectra: null
  montecarlo/mc_plot_covariances: null

  # Computation of the Transfer Function
  mm_transfer_function/compute_tf: null
  mm_transfer_function/plot_all_tf: null

  # Comparison of ACT and Planck
